# -*- coding: utf-8 -*-
"""anime recommender (2023).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOnwMwbL0VQsrZ6b3T3hSPfzwsGE3QEu
"""

!pip install "numpy<2"
!pip install scikit-surprise
# KHAI BÁO THƯ VIỆN
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.preprocessing import MinMaxScaler
from surprise import Reader, Dataset, SVD, accuracy
from surprise.model_selection import train_test_split
import pickle
from google.colab import files

# ==========================================
# 1: ĐỌC VÀ TIỀN XỬ LÝ DỮ LIỆU
# ==========================================
print("1. Đang tải và dọn dẹp dữ liệu...")

# Xử lý Anime
anime_df = pd.read_csv('/content/drive/MyDrive/Hybrid Anime Recommender System/anime-filtered.csv')
anime_df = anime_df.rename(columns={'Name': 'name', 'Genres': 'genre'})

# Điền giá trị rỗng cho các cột Text
anime_df['genre'] = anime_df['genre'].fillna('')
anime_df['sypnopsis'] = anime_df['sypnopsis'].fillna('')

# Xử lý Rating (Dùng 2 triệu dòng, ép kiểu để tối ưu RAM)
rating_df = pd.read_csv('/content/drive/MyDrive/Hybrid Anime Recommender System/user-filtered.csv',
                        nrows=2000000,
                        dtype={'user_id': 'int32', 'anime_id': 'int32', 'rating': 'int8'})

# Xóa điểm 0 (Người dùng lưu phim nhưng lười chấm điểm)
rating_df = rating_df[rating_df['rating'] > 0]

# Lọc dữ liệu thưa (Chỉ lấy User > 50 phim và Anime > 50 lượt vote)
min_anime_ratings = 50
filter_animes = rating_df['anime_id'].value_counts() > min_anime_ratings
filter_animes = filter_animes[filter_animes].index.tolist() # mang gom nhung id user > 50 phim

min_user_ratings = 50
filter_users = rating_df['user_id'].value_counts() > min_user_ratings
filter_users = filter_users[filter_users].index.tolist()

rating_df_clean = rating_df[(rating_df['anime_id'].isin(filter_animes)) & (rating_df['user_id'].isin(filter_users))]
print(f"-> Tổng số rating tinh khiết để train AI: {len(rating_df_clean)}")

# # co the bo sung train theo mo ta, dao dien, ...
# #2: HUẤN LUYỆN CONTENT-BASED
# print("\n2. Đang xây dựng ma trận nội dung (TF-IDF & Cosine)...")

# # ÉP MA TRẬN NHỎ LẠI
# valid_anime_ids = rating_df_clean['anime_id'].unique()
# anime_df = anime_df[anime_df['anime_id'].isin(valid_anime_ids)]

# tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 2), min_df=1, stop_words='english')
# tfidf_matrix = tf.fit_transform(anime_df['genre']) # Một ma trận toán học khổng lồ toàn số thập phân. Mỗi hàng là 1 anime, mỗi cột là 1 từ khoá, giá trị là điểm số TF-IDF.
# cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix) # đưa vào 2 lần để nó tự lấy từng anime so sánh với toàn bộ các anime còn lại

# # Tạo từ điển tra cứu nhanh
# anime_df = anime_df.reset_index(drop=True) # (VD: 0, 1, 4, 5, 9...), đánh số thứ tự hàng lại từ đầu cho đẹp: 0, 1, 2, 3... drop=True nghĩa là vứt bỏ luôn cái cột số thứ tự cũ đi.
# indices = pd.Series(anime_df.index, index=anime_df['name'])        # Tra theo Tên
# id_to_index = pd.Series(anime_df.index, index=anime_df['anime_id']) # Tra theo ID

# 2: HUẤN LUYỆN CONTENT-BASED & FEATURE ENGINEERING
print("\n2. Đang xây dựng hệ thống đặc trưng (Text & Heuristics)...")

# ÉP MA TRẬN NHỎ LẠI THEO TẬP RATING CLEAN
valid_anime_ids = rating_df_clean['anime_id'].unique()
anime_df = anime_df[anime_df['anime_id'].isin(valid_anime_ids)].copy()


# BƯỚC 2.1: XỬ LÝ TEXT (SYNOPISIS + GENRE) -> TF-IDF

# Tạo "Nồi lẩu văn bản" (Soup) gộp Thể loại và Tóm tắt
# Có thể nhân đôi cột genre để tăng trọng số của thể loại lên
anime_df['metadata_soup'] = anime_df['genre'] + " " + anime_df['genre'] + " " + anime_df['sypnopsis']

# Chạy TF-IDF trên metadata_soup (Lọc bỏ các từ vô nghĩa tiếng Anh như the, a, is...)
# Tăng min_df=2 để bỏ qua các từ quá hiếm, giúp giảm dung lượng RAM
tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 2), min_df=2, stop_words='english')
tfidf_matrix = tf.fit_transform(anime_df['metadata_soup']) # Một ma trận toán học khổng lồ toàn số thập phân. Mỗi hàng là 1 anime, mỗi cột là 1 từ khoá, giá trị là điểm số TF-IDF.

print("-> Đang tính toán Cosine Similarity...")
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix) # đưa vào 2 lần để nó tự lấy từng anime so sánh với toàn bộ các anime còn lại


# BƯỚC 2.2: XỬ LÝ CHỈ SỐ STATS (SCORE, DROPPED, MEMBERS) -> TRỌNG SỐ

# Điền số 0 cho các giá trị rỗng để tránh lỗi toán học
anime_df['Score'] = anime_df['Score'].fillna(0)
anime_df['Dropped'] = anime_df['Dropped'].fillna(0)
anime_df['Members'] = anime_df['Members'].replace(0, 1) # Tránh lỗi chia cho 0

# Tính Tỷ lệ Drop (Càng cao thì phim càng tệ)
anime_df['drop_rate'] = anime_df['Dropped'] / anime_df['Members']

# Chuẩn hóa Score (Scale từ 1-10 về khoảng 0-1 để dễ tính toán)
scaler = MinMaxScaler()
anime_df['normalized_score'] = scaler.fit_transform(anime_df[['Score']])

# TẠO CỘT 'quality_weight' (Trọng số chất lượng)
# Công thức: Base(1.0) + Thưởng điểm cho phim hay (tối đa +0.2) - Phạt điểm phim bị Drop nhiều (tối đa -0.3)
anime_df['quality_weight'] = 1.0 + (anime_df['normalized_score'] * 0.2) - (anime_df['drop_rate'] * 1.5)

# Đảm bảo trọng số không bao giờ rớt xuống số âm (Tối thiểu là 0.5)
anime_df['quality_weight'] = anime_df['quality_weight'].clip(lower=0.5)

print("-> Đã tổng hợp xong Trọng số Chất lượng (Quality Weight)!")


# BƯỚC 2.3: TẠO TỪ ĐIỂN TRA CỨU

anime_df = anime_df.reset_index(drop=True)
indices = pd.Series(anime_df.index, index=anime_df['name'])
id_to_index = pd.Series(anime_df.index, index=anime_df['anime_id'])

# LƯU Ý KHI XUẤT PKL: Đảm bảo cột 'quality_weight' và 'Score' vẫn nằm trong anime_df để Backend sử dụng

# 3: HUẤN LUYỆN COLLABORATIVE FILTERING (SVD) (USER-BASED)
print("\n3. Đang huấn luyện SVD và đo sai số (Có thể mất 1-2 phút)...")
reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(rating_df_clean[['user_id', 'anime_id', 'rating']], reader) # Nhồi dữ liệu Pandas biến thành bộ Dataset chuẩn của Surprise.
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

# Khởi tạo SVD với các siêu tham số chống học vẹt (Regularization)
svd_model = SVD(n_epochs=30, lr_all=0.005, reg_all=0.1, verbose=False) # Tắt verbose cho gọn màn hình
#lr_all=0.005 (Learning Rate): AI sẽ tự điều chỉnh bản thân sau mỗi lần đoán sai. Số này quy định nó sửa sai chậm hay nhanh. Lớn quá thì "ảo tưởng", nhỏ quá thì học quá lâu.
#reg_all=0.1 (Regularization - Phạt học vẹt): Ngăn chặn thuật toán dự đoán các mức điểm vô lý (ví dụ đoán điểm 15/10), giúp nó khiêm tốn và bám sát thực tế hơn.
svd_model.fit(trainset)

# Tính sai số
predictions = svd_model.test(testset)
print(f"-> RMSE CHÍNH THỨC CỦA HỆ THỐNG: {accuracy.rmse(predictions, verbose=False):.4f}")

# 4: HÀM HYBRID GỢI Ý (MULTI-INPUT BY ID)
def multi_input_hybrid_recommendation_by_id(user_ratings_dict):
    candidate_scores = {}
    watched_anime_ids = list(user_ratings_dict.keys())

    for anime_id, rating in user_ratings_dict.items():
        if anime_id in id_to_index:
            idx = id_to_index[anime_id]
            sim_scores = list(enumerate(cosine_sim[idx]))
            sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:21]

            for i, sim in sim_scores:
                candidate_id = anime_df.iloc[i]['anime_id']
                if candidate_id in watched_anime_ids:
                    continue

                score = sim * rating
                if candidate_id in candidate_scores:
                    candidate_scores[candidate_id] += score
                else:
                    candidate_scores[candidate_id] = score

    top_candidates = sorted(candidate_scores.items(), key=lambda x: x[1], reverse=True)[:10]
    result_indices = [id_to_index[cid] for cid, score in top_candidates]
    result_df = anime_df.iloc[result_indices][['anime_id', 'name', 'genre']].copy()
    result_df['hybrid_score'] = [score for cid, score in top_candidates]

    return result_df

# 5: CHẠY THỬ NGHIỆM (DEMO)

danh_sach_myanimelist_id = {
    19815: 10.0,  # No Game No Life
    30831: 10.0,  # KonoSuba
    1535: 606,    # Death Note
    38691: 9.0    # Dr. Stone: Stone Wars
}

print("\n=> KẾT QUẢ GỢI Ý CHO DANH SÁCH BẰNG ID:")
print(multi_input_hybrid_recommendation_by_id(danh_sach_myanimelist_id))

# 6: XUẤT FILE MODEL ĐỂ LÀM WEB APP
print("\n6. Đang đóng gói và lưu Models...")
with open('svd_model.pkl', 'wb') as f:
    pickle.dump(svd_model, f)

with open('cosine_sim.pkl', 'wb') as f:
    pickle.dump(cosine_sim, f)

anime_artifacts = {
    'dataframe': anime_df[['anime_id', 'name', 'genre']],
    'id_to_index': id_to_index,
    'indices': indices
}
with open('anime_artifacts.pkl', 'wb') as f:
    pickle.dump(anime_artifacts, f)

print("Đã lưu xong! Đang tải về máy...")
files.download('svd_model.pkl')
files.download('cosine_sim.pkl')
files.download('anime_artifacts.pkl')